Add HTTR model to the VTB
idaholab/virtual_test_bed pull request #275
Opened 2023-09-06 01:37 UTC by GiudGiud

closes #240

2023-09-06 01:43 UTC, moosebuild commented
Job [VTB Documentation](https://civet.inl.gov/job/1751542/) on fcc95d3 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/virtualtestbed/docs/PRs/275/site)

This comment will be updated on new commits.

2023-09-07 18:34 UTC, GiudGiud commented
@vincentlaboure if you want to have a last look before we release it

2023-09-07 18:46 UTC, vincentlaboure commented
Will do, thanks.

2023-09-07 20:27 UTC, vincentlaboure requested changes
Looks good to me. Just a typo to fix.

2023-09-07 20:47 UTC, GiudGiud commented on doc/content/resources/codes_used.md
> +- HTTR Core multiphysics [documentation](httf/index.md) and [inputs](https://github.com/idaholab/virtual_test_bed/tree/main/htgr/httr/steady_state_and_null_transient)
done. good catch, thank you for taking a look

2023-09-07 21:57 UTC, vincentlaboure approved these changes

2023-09-07 22:03 UTC, merged