Adding Mastodon to VTB
idaholab/virtual_test_bed pull request #396
Opened 2024-06-12 16:59 UTC by kyleeswanson

Adding Mastodon to VTB per Guillaume's instruction

2024-06-12 17:04 UTC, GiudGiud commented on doc/content/seismic_analysis/mastoson.md
mastoson -> npp_building.md

2024-06-12 18:05 UTC, kyleeswanson commented on seismic_analysis/basemat_with_isolators_new.i
> +  [DynamicTensorMechanics]
What is the syntax? I'm not seeing any other Kernel types that are relevant

2024-06-12 18:51 UTC, GiudGiud commented on seismic_analysis/basemat_with_isolators_new.i
> +  [DynamicTensorMechanics]
see the dynamics input for examples
https://github.com/idaholab/moose/blob/next/modules/solid_mechanics/test/tests/dynamics/time_integration/newmark_action.i

2024-06-21 17:05 UTC, moosebuild commented
Job [VTB Documentation](https://civet.inl.gov/job/2290215/) on d20f33f wanted to post the following:

View the site [here](https://mooseframework.inl.gov/virtualtestbed/docs/PRs/396/site)

This comment will be updated on new commits.

2024-06-27 02:48 UTC, GiudGiud commented on seismic_analysis/mesh/full_structure_with_isolators_new.e
let's use LFS for that. I ll show you tomorrow

2024-06-27 02:49 UTC, GiudGiud commented on seismic_analysis/tests
tests all pass, good job

2024-06-27 03:06 UTC, GiudGiud commented on seismic_analysis/tests
> +    method = opt
```suggestion
```
pls remove those from syntax tests, they are cheap

2024-07-02 16:17 UTC, GiudGiud requested changes

2024-07-02 16:17 UTC, GiudGiud commented on doc/content/seismic_analysis/npp_building/npp_building_pt2.md
> +All the materials in the building are modeled using a linear elastic material and 3D 8-noded HEX elements, except for the FP isolators, which are modeled using two noded link elements with the FP iso
```suggestion
All the materials in the building are modeled using a linear elastic material and 3D 8-noded HEX elements, except for the FP isolators, which are modeled using two noded link elements with the FP isolator material model see MASTODON [theory manual](https://mooseframework.inl.gov/mastodon/manuals/theory/index.html) and [user manual](https://mooseframework.inl.gov/mastodon/manuals/user/index.html) for more information. The reactor vessel is modeled as a thin cylindrical vessel using continuum elements. The fluid inside the reactor vessel is modeled using a linear elastic material with a very small shear modulus to reproduce fluid-like behavior. A more comprehensive, fluid-structure interaction (FSI) approach is also possible in MASTODON to model the fluid. More information on FSI modeling in MOOSE and MASTODON is provided [here](https://mooseframework.inl.gov/modules/fsi/index.html). Further information on the building model is also provided in [!citet](inl-ext-20-59608).
```

2024-07-02 16:17 UTC, GiudGiud commented on seismic_analysis/mesh/full_structure_with_isolators_new.e
this is too big let's use LFS for it

2024-07-02 22:48 UTC, GiudGiud reviewed
fails the vtb tests now. 
It looks like a file got lost in the folder change

2024-07-03 19:32 UTC, GiudGiud commented
@cbolisetti if you have time to take a look

2024-07-08 23:20 UTC, cbolisetti commented
@GiudGiud and @kyleeswanson looks good to me. Can you please also mention somewhere that this was adopted from the list of examples on the Mastodon website and link it to the examples page? Perhaps at the beginning of both Part 1 and Part 2?

2024-07-09 05:53 UTC, GiudGiud commented
good idea. Let's also add Chandu as the POC on top of the relevant page, as well as a link to the models (from the doc page)

2024-07-10 13:56 UTC, GiudGiud commented on doc/content/msr/msr_generic/seismic_analysis/npp_building/npp_building_pt1.md
> +This model was adopted from the list of examples on the [MASTODON](https://mooseframework.inl.gov/mastodon/examples/index.html) website.
add a link to the inputs on the virtual test bed
somewhere like https://github.com/idaholab/virtual_test_bed/tree/devel/msr/msr_generic/seismic_analysis

2024-07-10 13:57 UTC, GiudGiud commented on doc/content/msr/msr_generic/seismic_analysis/npp_building/npp_building_pt2.md
> +This model was adopted from the list of examples on the [MASTODON](https://mooseframework.inl.gov/mastodon/examples/index.html) website.
same

2024-07-10 13:57 UTC, GiudGiud commented on doc/content/msr/msr_generic/seismic_analysis/index.md
> +
add a tag. see other model doco for the tagging syntax

2024-07-15 15:26 UTC, GiudGiud commented
the tags are not displaying
https://mooseframework.inl.gov/virtualtestbed/docs/PRs/396/site/resources/filter/index.html

2024-07-15 15:32 UTC, GiudGiud commented on doc/content/msr/msr_generic/seismic_analysis/npp_building/npp_building_pt1.md
> +                       simulation_type:seismic analysis
```suggestion
```

2024-07-15 15:32 UTC, GiudGiud commented on doc/content/msr/msr_generic/seismic_analysis/npp_building/npp_building_pt2.md
> +                       simulation_type:seismic analysis
```suggestion
```

2024-07-15 15:32 UTC, GiudGiud commented on doc/content/msr/msr_generic/seismic_analysis/npp_building/npp_building_pt1.md
> +                       simulation_type:seismic analysis
no need to duplicate tags

2024-07-15 15:32 UTC, GiudGiud commented on doc/content/msr/msr_generic/seismic_analysis/index.md
> +This model was adopted from the list of examples on the [MASTODON](https://mooseframework.inl.gov/mastodon/examples/index.html) website. For further information regarding [MASTODON](https://moosefram
Chandu is a short version of his name

use Dr. Bolisetti instead

2024-07-15 20:58 UTC, GiudGiud approved these changes

2024-07-16 02:26 UTC, GiudGiud commented
The LFS include is still not working properly. Let s fix this tomorrow

2024-07-17 22:15 UTC, GiudGiud commented
Test failures unrelated

2024-07-17 22:16 UTC, GiudGiud approved these changes

2024-07-17 22:16 UTC, merged