KRUSTY Multiphysics Model
idaholab/virtual_test_bed pull request #404
Opened 2024-07-03 17:44 UTC by aabdelhameedd

2024-07-03 19:20 UTC, GiudGiud requested changes
thanks for the contribution. I foresee this as one of the most influential contributions to the VTB this year given the importance of KRUSTY. I think the formatting will need to be impeccable, I left some directions to use MooseDocs better. Please apply them throughout every page of the documentation

2024-07-06 03:55 UTC, moosebuild commented
Job [VTB Documentation](https://civet.inl.gov/job/2314168/) on 2216a7f wanted to post the following:

View the site [here](https://mooseframework.inl.gov/virtualtestbed/docs/PRs/404/site)

This comment will be updated on new commits.

2024-07-10 20:25 UTC, miaoyinb commented
@GiudGiud Thanks for the review. I think we resolved all the comments. It should be ready for another round of review.

I added some syntax check tests and mesh gen tests. Not sure if we want regression tests as these are kind of heavy.

2024-07-10 21:17 UTC, GiudGiud commented
can you run a single timestep for the BISON case? 
and what about an eigenvalue calculation without multiphysics for the Griffin one?
how expensive would each of those be?
we have access to a beefier machine for Griffin now, within reason we can make some larger cases work

2024-07-10 21:29 UTC, ycao-anl commented
The Griffin neutronic alone calculation on sawtooth is roughly about 12 minutes with 640 CPUs if using NA=3, SN35.
For NA=1 and SN13, the run time can be 20 times faster.
Yan

From: Guillaume Giudicelli ***@***.***>
Sent: Wednesday, July 10, 2024 4:18 PM
To: idaholab/virtual_test_bed ***@***.***>
Cc: Cao, Yan ***@***.***>; Assign ***@***.***>
Subject: Re: [idaholab/virtual_test_bed] KRUSTY Multiphysics Model (PR #404)

can you run a single timestep for the BISON case? and what about an eigenvalue calculation without multiphysics for the Griffin one? how expensive would each of those be? we have access to a beefier machine for Griffin now, within reason we
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

can you run a single timestep for the BISON case?
and what about an eigenvalue calculation without multiphysics for the Griffin one?
how expensive would each of those be?
we have access to a beefier machine for Griffin now, within reason we can make some larger cases work

—
Reply to this email directly, view it on GitHub<https://urldefense.us/v3/__https:/github.com/idaholab/virtual_test_bed/pull/404*issuecomment-2221496270__;Iw!!G_uCfscf7eWS!dpTHmxfrOxit8_Zfl7FMbY_AcgW47jq_7pd5L-eDIk2eqAzok3xEPVX11Lq3AxSKcGAd_vr7ceYv7hsGrdL91w$>, or unsubscribe<https://urldefense.us/v3/__https:/github.com/notifications/unsubscribe-auth/BJUPMMEVCCIEDORCLZSXJKTZLWQH3AVCNFSM6AAAAABKKBIQO6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEMRRGQ4TMMRXGA__;!!G_uCfscf7eWS!dpTHmxfrOxit8_Zfl7FMbY_AcgW47jq_7pd5L-eDIk2eqAzok3xEPVX11Lq3AxSKcGAd_vr7ceYv7hsPQQen5w$>.
You are receiving this because you were assigned.Message ID: ***@***.******@***.***>>

2024-07-10 21:51 UTC, GiudGiud commented
> For NA=1 and SN13, the run time can be 20 times faster.

that seems workable. The tests can modify the input through cli_args so we can afford to run that for regression

2024-07-11 18:55 UTC, miaoyinb commented
Regression cases added.

2024-07-15 17:03 UTC, miaoyinb commented
@GiudGiud just a friendly reminder that this PR is ready for another round of review. Thanks.

2024-07-15 17:45 UTC, GiudGiud commented
Hello!

I'll get to it once our giant submodule update PR makes it through.
Thansk for reaching it out

2024-08-12 16:35 UTC, miaoyinb commented
@GiudGiud Just a friendly reminder that this is still pending review. Thanks in advance.

2024-08-12 17:46 UTC, GiudGiud commented
will do! thanks for the reminder.

2024-08-14 04:15 UTC, GiudGiud requested changes
minor things. I ll test the inputs tomorrow probably on HPC

2024-08-14 04:15 UTC, GiudGiud commented on doc/content/microreactors/KRUSTY/Griffin-BISON_Multiphysics_Model.md
> +Finally, [axial_output] shows the steps to tally the axial power distribution in the KRUSTY innermost (“r1”) layer. To integrate the fission power within each fuel layer (seven radial layers), an Aux
```suggestion
Finally, [axial_output] shows the steps to tally the axial power distribution in the KRUSTY innermost (“r1”) layer. To integrate the fission power within each fuel layer (seven radial layers), an `AuxVariable` in MOOSE that can be processed by the `VectorPostprocessor` was first defined to hold the layer-integrated total fission power for the axial regions within that layer as shown in the first block of [axial_output]. A `UserObject` as shown in the second block of [axial_output] was necessary to perform the actual integration among the different axial layers. The integrated values were then placed into the `AuxVariable` as shown in the third block of [axial_output] and were printed out by the `VectorPostprocessor` as shown in the fourth block of [axial_output].
```
to be consistent with the beginning of the text

2024-08-14 04:15 UTC, GiudGiud commented on doc/content/microreactors/KRUSTY/Griffin-BISON_Multiphysics_Model.md
> +For a thermo-mechanical model, thermophysical properties (i.e., thermal conductivity, density, specific heat, and thermal expansion coefficient) and mechanical properties (i.e., elastic modulus) of a
```suggestion
For a thermo-mechanical model, thermophysical properties (i.e., thermal conductivity, density, specific heat, and thermal expansion coefficient) and mechanical properties (i.e., elastic modulus) of all the involved components are needed. [thm_model] lists the BISON/MOOSE models used for thermo-mechanical simulations. BISON doesn't include models for KRUSTY’s U-7.65Mo fuel material, so the thermal conductivity of U-10Mo and specific heat of U-8Mo are currently applied. Other thermal and mechanical attributes for U-7.65Mo and B4C were sourced from the open literature or based on certain assumptions. The displacements in the “soft materials” regions are not solved using MOOSE’s solid mechanics solver as the solid components. Instead, simple diffusion is used for these regions to simply propagate the deformation of the solid components.
```

2024-08-14 04:15 UTC, GiudGiud commented on doc/content/microreactors/KRUSTY/Griffin-BISON_Multiphysics_Model.md
> +The movement of the axial reflector to insert the reactivity was modeled by forcing a Dirichlet boundary condition on the bottom of the solid assembly that includes the axial reflector to allow BISON
tensor -> solid

2024-08-14 04:15 UTC, GiudGiud commented on doc/content/microreactors/KRUSTY/Griffin-BISON_Multiphysics_Model.md
> +The movement of the axial reflector to insert the reactivity was modeled by forcing a Dirichlet boundary condition on the bottom of the solid assembly that includes the axial reflector to allow BISON
```suggestion
The movement of the axial reflector to insert the reactivity was modeled by forcing a Dirichlet boundary condition on the bottom of the solid assembly that includes the axial reflector to allow BISON to calculate the consequent displacement field through solving solid mechanics equations. Two steady-state eigenvalue calculations were included in the VTB model. These calculations were performed to confirm that an adequate amount of external reactivity was introduced for initiating the transient. The first one corresponds to the initial steady state for future transient simulation, and the second steady state corresponds to the first step of the transient after the reflector is shifted upward. In this calculation, the bias in the axial direction was set in the BISON input as shown in [mov_refl] to generate the displacement in the mesh. The displacements were passed to Griffin neutronic for calculating the total reactivity inserted into the reactor using the MultiApp coupling framework.
```

2024-08-15 00:04 UTC, GiudGiud commented
to reduce the picture size you must remove it from the commit that introduced it. Otherwise it does not change anything with regards to the repository size

2024-08-15 00:14 UTC, miaoyinb commented
> to reduce the picture size you must remove it from the commit that introduced it. Otherwise it does not change anything with regards to the repository size

Will do. I am working on the other comments and will do a rebase once everything looks fine.

2024-08-15 15:13 UTC, moosebuild commented
Job [MOOSE](https://civet.inl.gov/job/2386494/) on b995bbd : invalidated by @miaoyinb

2024-08-19 15:47 UTC, GiudGiud commented
looks like it does not converge on HPC for me.
We could be getting unlucky, what is the exact configuration you ran? 15 nodes * 40 procs?

alternatively we should change BISON to not error but rather to use the solutionInvalidInterface here

[log.txt](https://github.com/user-attachments/files/16662555/log.txt)

2024-08-19 16:09 UTC, GiudGiud commented
for the input as is (not changing the azimuthal, so 3,5,3) what did you use?

2024-08-19 16:10 UTC, miaoyinb commented
I used 2 3 3

2024-08-19 16:24 UTC, GiudGiud commented
I imagine 2,3,3 works fine?

@aabdelhameedd what was the configuration to run the input as it is currently ?

2024-08-19 16:43 UTC, miaoyinb commented
I think we only use 3 5 3 for neutronics only. How many nodes did you use? @ycao-anl

2024-08-19 16:51 UTC, ycao-anl commented
I used 640 CPUs.

Yan

From: Yinbin Miao ***@***.***>
Sent: Monday, August 19, 2024 11:44 AM
To: idaholab/virtual_test_bed ***@***.***>
Cc: Cao, Yan ***@***.***>; Mention ***@***.***>
Subject: Re: [idaholab/virtual_test_bed] KRUSTY Multiphysics Model (PR #404)

I think we only use 3 5 3 for neutronics only. How many nodes did you use? @ycao-anl — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: <idaholab/virtual_test_bed/pull/404/c2296997762@ github. com>
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

I think we only use 3 5 3 for neutronics only. How many nodes did you use? @ycao-anl<https://urldefense.us/v3/__https:/github.com/ycao-anl__;!!G_uCfscf7eWS!ZgqJOEp9MbrDFJy7F7-aa7SGsg63cQHj_tI4x_SqS511TZ8O44QVRCnbmYnRvVkoivz8luUi95s_R03k8_ldiw$>

—
Reply to this email directly, view it on GitHub<https://urldefense.us/v3/__https:/github.com/idaholab/virtual_test_bed/pull/404*issuecomment-2296997762__;Iw!!G_uCfscf7eWS!ZgqJOEp9MbrDFJy7F7-aa7SGsg63cQHj_tI4x_SqS511TZ8O44QVRCnbmYnRvVkoivz8luUi95s_R03JxQxXvQ$>, or unsubscribe<https://urldefense.us/v3/__https:/github.com/notifications/unsubscribe-auth/BJUPMMEZ65UQ2KJZHJXPWSLZSIOELAVCNFSM6AAAAABKKBIQO6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOJWHE4TONZWGI__;!!G_uCfscf7eWS!ZgqJOEp9MbrDFJy7F7-aa7SGsg63cQHj_tI4x_SqS511TZ8O44QVRCnbmYnRvVkoivz8luUi95s_R02H0-IR2w$>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2024-08-19 16:57 UTC, GiudGiud commented
how did you do 640 on sawtooth?  16 nodes with 40 cpus each?
asking because sawtooth has 48 cpus per node

2024-08-19 17:05 UTC, miaoyinb commented
Ah, for the multiphysics simulations, the power needs to be reduced as the model is for the warm critical tests without heat pipe heat removal. I will fix it soon. We use 0.01 W for steady state as the power only rises to ~900W during reactivity insertion transient.

2024-08-19 17:05 UTC, ycao-anl commented
Yes, I used 40 cpus and 16 nodes.


From: Guillaume Giudicelli ***@***.***>
Sent: Monday, August 19, 2024 11:58 AM
To: idaholab/virtual_test_bed ***@***.***>
Cc: Cao, Yan ***@***.***>; Mention ***@***.***>
Subject: Re: [idaholab/virtual_test_bed] KRUSTY Multiphysics Model (PR #404)

how did you do 640 on sawtooth? 16 nodes with 40 cpus each? asking because sawtooth has 48 cpus per node — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: 
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

how did you do 640 on sawtooth? 16 nodes with 40 cpus each?
asking because sawtooth has 48 cpus per node

—
Reply to this email directly, view it on GitHub<https://urldefense.us/v3/__https:/github.com/idaholab/virtual_test_bed/pull/404*issuecomment-2297022681__;Iw!!G_uCfscf7eWS!b5YoHGT_FJQnC-dORaYKOLBcLDlUsXN8yubFRK9C8w3z0RrBwoghFk4TtxZ4Em1DFrQBr0kiyB66E53tHPIxQw$>, or unsubscribe<https://urldefense.us/v3/__https:/github.com/notifications/unsubscribe-auth/BJUPMMDKHUI6WHO7OQGD6NTZSIPZ5AVCNFSM6AAAAABKKBIQO6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOJXGAZDENRYGE__;!!G_uCfscf7eWS!b5YoHGT_FJQnC-dORaYKOLBcLDlUsXN8yubFRK9C8w3z0RrBwoghFk4TtxZ4Em1DFrQBr0kiyB66E533XIpJvg$>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2024-08-19 17:23 UTC, GiudGiud commented
Sounds good.
Thanks @miaoyinb we should be able to roll this out soon then! VTB testing is back on now too

2024-08-19 21:06 UTC, GiudGiud commented
I'll take it from here @miaoyinb I was waiting for the recipes to update. I think you merged it right on time though

2024-08-20 00:32 UTC, GiudGiud commented
Test failures are unrelated, on other modles, and being addressed in current maintenance operations

2024-08-20 00:33 UTC, GiudGiud approved these changes
merging once Griffin testing completes

2024-08-20 03:59 UTC, GiudGiud commented on microreactors/KRUSTY/tests
> +      allow_warnings = true
```suggestion
      allow_warnings = true
      # Too slow
      method = 'devel'
```

2024-08-20 03:59 UTC, GiudGiud commented on microreactors/KRUSTY/tests
> +      method = 'devel'
```suggestion
      method = 'opt'
```

2024-08-20 16:38 UTC, GiudGiud commented
Cardinal failure unrelated, DW recipe crashed but passed earlier

2024-08-20 16:38 UTC, merged

2024-08-20 16:38 UTC, GiudGiud commented
Thanks for the contribution @aabdelhameedd @ycao-anl @miaoyinb !